"""Constants and such that are shared between client and server."""

SUCCESS = 200
INVALID_METHOD = 400
UNHANDLED_ERROR = 503

ENV_CONFIGNAME = 'DCCAUTO_CONFIGNAME'
ENV_HANDSHAKE_ENDPOINT = 'DCCAUTO_HANDSHAKE_ENDPOINT'

ENV_APP_ENDPOINT = 'DCCAUTO_APP_ENDPOINT'

ENV_INPROC_PORT = 'DCCAUTO_INPROC_PORT'