"""Constants and such that are shared between client and server."""

SUCCESS = 200
INVALID_METHOD = 400
UNHANDLED_ERROR = 503

ENV_CONFIGNAME = 'DCCAUTO_CONFIGNAME'
ENV_HANDSHAKE = 'DCCAUTO_HANDSHAKE'

ENV_APP_ENDPOINT = 'DCCAUTO_APP_ENDPOINT'